import { loadAppEnv, type AppEnv } from "@99freelas/config";

export type WorkerEnv = Pick<
  AppEnv,
  | "NODE_ENV"
  | "AUTOMATION_MODE"
  | "SUPABASE_URL"
  | "SUPABASE_SERVICE_ROLE_KEY"
  | "SUPABASE_STORAGE_BUCKET"
  | "REDIS_URL"
  | "LLM_PROVIDER"
  | "OPENAI_API_KEY"
  | "OPENAI_MODEL"
  | "LLM_TEMPERATURE"
  | "LLM_MAX_TOKENS"
  | "PRICE_DISCOUNT_FACTOR"
  | "MIN_PROPOSAL_AMOUNT_BRL"
  | "MIN_DAILY_RATE_BRL"
  | "DEFAULT_HOURLY_RATE_BRL"
  | "DEADLINE_REDUCTION_FACTOR"
  | "MIN_DEADLINE_DAYS"
  | "MAX_DEADLINE_DAYS"
  | "AUTO_SUBMIT_ONLY_WITH_CLEAR_SCOPE"
  | "AUTO_SUBMIT_ONLY_WITH_AVERAGE_BID"
  | "REJECT_UNCLEAR_SCOPE_WHEN_AUTOPILOT"
  | "BROWSER_HEADLESS"
  | "BROWSER_STORAGE_STATE_PATH"
>;

export function loadWorkerEnv(source: NodeJS.ProcessEnv = process.env): WorkerEnv {
  const env = loadAppEnv(source);

  return {
    NODE_ENV: env.NODE_ENV,
    AUTOMATION_MODE: env.AUTOMATION_MODE,
    SUPABASE_URL: env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: env.SUPABASE_SERVICE_ROLE_KEY,
    SUPABASE_STORAGE_BUCKET: env.SUPABASE_STORAGE_BUCKET,
    REDIS_URL: env.REDIS_URL,
    LLM_PROVIDER: env.LLM_PROVIDER,
    OPENAI_API_KEY: env.OPENAI_API_KEY,
    OPENAI_MODEL: env.OPENAI_MODEL,
    LLM_TEMPERATURE: env.LLM_TEMPERATURE,
    LLM_MAX_TOKENS: env.LLM_MAX_TOKENS,
    PRICE_DISCOUNT_FACTOR: env.PRICE_DISCOUNT_FACTOR,
    MIN_PROPOSAL_AMOUNT_BRL: env.MIN_PROPOSAL_AMOUNT_BRL,
    MIN_DAILY_RATE_BRL: env.MIN_DAILY_RATE_BRL,
    DEFAULT_HOURLY_RATE_BRL: env.DEFAULT_HOURLY_RATE_BRL,
    DEADLINE_REDUCTION_FACTOR: env.DEADLINE_REDUCTION_FACTOR,
    MIN_DEADLINE_DAYS: env.MIN_DEADLINE_DAYS,
    MAX_DEADLINE_DAYS: env.MAX_DEADLINE_DAYS,
    AUTO_SUBMIT_ONLY_WITH_CLEAR_SCOPE: env.AUTO_SUBMIT_ONLY_WITH_CLEAR_SCOPE,
    AUTO_SUBMIT_ONLY_WITH_AVERAGE_BID: env.AUTO_SUBMIT_ONLY_WITH_AVERAGE_BID,
    REJECT_UNCLEAR_SCOPE_WHEN_AUTOPILOT: env.REJECT_UNCLEAR_SCOPE_WHEN_AUTOPILOT,
    BROWSER_HEADLESS: env.BROWSER_HEADLESS,
    BROWSER_STORAGE_STATE_PATH: env.BROWSER_STORAGE_STATE_PATH,
  };
}
