export const selectors99Freelas = {
  loginUrl: "https://www.99freelas.com.br/login",
  dashboardUrl: "https://www.99freelas.com.br/projetos",
  projectListUrl: "https://www.99freelas.com.br/projects",
  homeUrl: "https://www.99freelas.com.br/",
  authenticatedMarkers: [
    'a[href*="logout"]',
    'a[href*="sair"]',
    'a[href*="/dashboard"]',
    'a[href*="/projetos"]',
    'a[href*="/mensagens"]',
    'a[href*="/perfil"]',
    '[data-testid="user-menu"]',
  ],
  loginMarkers: [
    'input[type="email"]',
    'input[name="email"]',
    'input[name="login"]',
    'input[type="password"]',
    'button[type="submit"]',
  ],
  projectTitle: '[data-testid="project-title"], h1',
  projectDescription: '[data-testid="project-description"], .project-description',
  averageBidLabel: "Valor médio das propostas:",
  averageDeadlineLabel: "Duração média estimada:",
  connectionsLabel: "Esta proposta requer",
  proposalForm: "#formProposta, form:has(#btnConcluirEnvioProposta), form:has(#proposta)",
  proposalAmountInput: "#oferta",
  proposalFinalAmountInput: "#oferta-final",
  proposalDeadlineInput: "#duracao-estimada",
  proposalDetailsTextarea: "#proposta",
  minimumOfferText: '(Oferta mínima:',
  submitButton: "#btnConcluirEnvioProposta",
  askQuestionLink: 'a[href*=\"/project/message/\"]',
} as const;
